# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: Project3.{build}-{branch}
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: C:\projects\TempMotor3D_P3

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Win32

# build Configuration, i.e. Debug, Release, etc.
configuration:
- Debug
- Release

build:
  project: Engine\Culverin.sln
  
  # MSBuild verbosity level
  verbosity: normal
  
#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:		
      - martimyc@gmail.com
      - nico.babotaltisen@gmail.com
      - andreu.rbj@gmail.com
      - jordior97@gmail.com
      - yotolivenza@gmail.com
      - mizquierdo97@gmail.com
      - marcfv97@gmail.com
      - elliot.jimenez1@gmail.com
      - ferranmartinvila21@gmail.com
      - adriancl1996@gmail.com
      - imbecilustotalus@gmail.com
      - marc.lafrwy@gmail.com
      - pere.rifaplanellas@gmail.com
      - josef21296@gmail.com
      - carcasanchez@gmail.com
      - th_sola@hotmail.com
      - dlopez3a@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false
